/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-archive.h
 #	source generated by 4D Plugin Wizard
 #	Project : archive
 #	author : miyako
 #	2021/04/29
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_ARCHIVE_H
#define PLUGIN_ARCHIVE_H

#include "4DPluginAPI.h"

#include "4DPlugin-JSON.h"

#include "archive.h"

#pragma mark -

void archive_read(PA_PluginParameters params);
void archive_write(PA_PluginParameters params);
void archive_version(PA_PluginParameters params);

#endif /* PLUGIN_ARCHIVE_H */
